[project]
name = "eval"
version = "0.1.0"
description = "Running evaluation scripts for VLLM models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "pandas>=2.3.3",
    "torch>=2.8.0",
    "vllm>=0.10.2",
]
